feat: change user preferences to user keywords
jahorwitz/slopopedia-api pull request #16
Opened 2024-05-29 01:34 UTC by marzahlde09

## Describe your changes

-Preferences table dropped
-User Preference changed to User Keyword
-Foreign key dependencies updated
-Migration file was modified so User Preference was not dropped, and instead altered data

## Issue ticket number and link

[Slop-90](https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-90)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If there are changes to custom resolvers, I have added / updated automated tests
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-05-29 02:18 UTC, bduckdev approved these changes
nice work. does anything on the front end need to be updated along with this?

2024-05-29 15:44 UTC, marzahlde09 commented
I'm expecting front end changes to come later - user keywords are going to get mixed in with the "recommendations" as well of course! I figure making sure this works independently is a good first step

2024-05-30 22:00 UTC, skovakina requested changes
I believe we should discuss this change further. According to Figma and the concept of preferences, almost every keyword should be associated with a specific group of preferences. So, instead of deleting preferences, we should focus on connecting them to the keywords. 
![image](https://github.com/jahorwitz/slopopedia-api/assets/70713202/d19732fd-f3e2-4c10-986d-d73292b246fd)
We can also see this in the data: keywords, handicap, and KWType (aka preferences) that were deleted in this PR
![image](https://github.com/jahorwitz/slopopedia-api/assets/70713202/29d329d1-488b-4792-b260-2a1232089cf3)

2024-05-31 00:40 UTC, marzahlde09 commented
I followed the AC, and this should allow users to have scores for different keywords. The user-keyword table is connected to keywords, which has the keyword-type, so that relationship still exists.

2024-06-03 16:47 UTC, skovakina approved these changes
alright. I think you've done a good job here

2024-06-04 15:40 UTC, tomershvueli requested changes, later dismissed
See 1 comment, and also let's sync with the latest from `main`.

2024-06-04 15:40 UTC, tomershvueli commented on migrations/20240529004854_change_user_preference_to_user_keyword/migration.sql
> +ALTER TABLE `userpreference` DROP FOREIGN KEY `UserPreference_preference_fkey`;
Let's fix the capitalization on these tables.

2024-06-22 15:14 UTC, Thatalent approved these changes
LGTM

2024-06-22 15:14 UTC, merged